---
application:
  name: "api-wilayah-administrasi-indonesia"
  project: "wilayah-administrasi-indonesia"
  organization: "QoveryCommunity"
routers:
- name: "main-api-wilayah-administrasi-indonesia"
  routes:
  - application_name: "api-wilayah-administrasi-indonesia"
    paths:
    - "/*"
